[2024-12-21T15:18:52.434+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-21T15:18:52.470+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fintech_etl_pipeline.run_dashboard manual__2024-12-21T15:18:17.684624+00:00 [queued]>
[2024-12-21T15:18:52.491+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fintech_etl_pipeline.run_dashboard manual__2024-12-21T15:18:17.684624+00:00 [queued]>
[2024-12-21T15:18:52.492+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-21T15:18:52.562+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_dashboard> on 2024-12-21 15:18:17.684624+00:00
[2024-12-21T15:18:52.579+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=619) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-21T15:18:52.582+0000] {standard_task_runner.py:72} INFO - Started process 628 to run task
[2024-12-21T15:18:52.582+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fintech_etl_pipeline', 'run_dashboard', 'manual__2024-12-21T15:18:17.684624+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/fintech_dag.py', '--cfg-path', '/tmp/tmpij88e3rv']
[2024-12-21T15:18:52.587+0000] {standard_task_runner.py:105} INFO - Job 105: Subtask run_dashboard
[2024-12-21T15:18:52.656+0000] {task_command.py:467} INFO - Running <TaskInstance: fintech_etl_pipeline.run_dashboard manual__2024-12-21T15:18:17.684624+00:00 [running]> on host b2048de23098
[2024-12-21T15:18:52.821+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Zeyad_Habash' AIRFLOW_CTX_DAG_ID='fintech_etl_pipeline' AIRFLOW_CTX_TASK_ID='run_dashboard' AIRFLOW_CTX_EXECUTION_DATE='2024-12-21T15:18:17.684624+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-21T15:18:17.684624+00:00'
[2024-12-21T15:18:52.822+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-21T15:18:52.863+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-21T15:18:52.880+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'streamlit run /opt/***/dags/fintech_dashboard.py -- --filename /opt/***/data/fintech_clean.parquet --lookup_table_filename /opt/***/data/lookup_table.csv']
[2024-12-21T15:18:52.927+0000] {subprocess.py:99} INFO - Output:
[2024-12-21T15:18:55.183+0000] {subprocess.py:106} INFO - 
[2024-12-21T15:18:55.184+0000] {subprocess.py:106} INFO - Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.
[2024-12-21T15:18:55.185+0000] {subprocess.py:106} INFO - 
[2024-12-21T15:18:56.596+0000] {subprocess.py:106} INFO - 
[2024-12-21T15:18:56.604+0000] {subprocess.py:106} INFO -   You can now view your Streamlit app in your browser.
[2024-12-21T15:18:56.606+0000] {subprocess.py:106} INFO - 
[2024-12-21T15:18:56.611+0000] {subprocess.py:106} INFO -   Local URL: http://localhost:8501
[2024-12-21T15:18:56.612+0000] {subprocess.py:106} INFO -   Network URL: http://172.18.0.6:8501
[2024-12-21T15:18:56.615+0000] {subprocess.py:106} INFO -   External URL: http://102.41.22.125:8501
[2024-12-21T15:18:56.616+0000] {subprocess.py:106} INFO - 
[2024-12-21T15:22:19.310+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-12-21T15:22:19.314+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-21T15:22:19.317+0000] {process_utils.py:132} INFO - Sending 15 to group 628. PIDs of all processes in the group: [630, 628]
[2024-12-21T15:22:19.318+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 628
[2024-12-21T15:22:19.319+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-21T15:22:19.322+0000] {subprocess.py:117} INFO - Sending SIGTERM signal to process group
[2024-12-21T15:22:19.362+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-12-21T15:22:19.396+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fintech_etl_pipeline, task_id=run_dashboard, run_id=manual__2024-12-21T15:18:17.684624+00:00, execution_date=20241221T151817, start_date=20241221T151852, end_date=20241221T152219
[2024-12-21T15:22:19.439+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-21T15:22:19.856+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=628, status='terminated', exitcode=2, started='15:18:52') (628) terminated with exit code 2
[2024-12-21T15:22:19.910+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=630, status='terminated', started='15:18:52') (630) terminated with exit code None
