[2024-12-19T21:42:11.882+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T21:42:11.919+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fintech_etl_pipeline.run_dashboard manual__2024-12-19T21:39:28.868330+00:00 [queued]>
[2024-12-19T21:42:11.936+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fintech_etl_pipeline.run_dashboard manual__2024-12-19T21:39:28.868330+00:00 [queued]>
[2024-12-19T21:42:11.937+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 3
[2024-12-19T21:42:11.973+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_dashboard> on 2024-12-19 21:39:28.868330+00:00
[2024-12-19T21:42:11.993+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning:

This process (pid=371) is multi-threaded, use of fork() may lead to deadlocks in the child.


[2024-12-19T21:42:11.998+0000] {standard_task_runner.py:72} INFO - Started process 389 to run task
[2024-12-19T21:42:12.008+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fintech_etl_pipeline', 'run_dashboard', 'manual__2024-12-19T21:39:28.868330+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/fintech_dag.py', '--cfg-path', '/tmp/tmpeks4cx2k']
[2024-12-19T21:42:12.010+0000] {standard_task_runner.py:105} INFO - Job 42: Subtask run_dashboard
[2024-12-19T21:42:12.093+0000] {task_command.py:467} INFO - Running <TaskInstance: fintech_etl_pipeline.run_dashboard manual__2024-12-19T21:39:28.868330+00:00 [running]> on host 3f9b1cd285db
[2024-12-19T21:42:12.210+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Zeyad_Habash' AIRFLOW_CTX_DAG_ID='fintech_etl_pipeline' AIRFLOW_CTX_TASK_ID='run_dashboard' AIRFLOW_CTX_EXECUTION_DATE='2024-12-19T21:39:28.868330+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-19T21:39:28.868330+00:00'
[2024-12-19T21:42:12.211+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T21:42:12.237+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-19T21:42:12.243+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'streamlit run ./fintech_dashboard.py']
[2024-12-19T21:42:12.266+0000] {subprocess.py:99} INFO - Output:
[2024-12-19T21:42:14.393+0000] {subprocess.py:106} INFO - Usage: streamlit run [OPTIONS] TARGET [ARGS]...
[2024-12-19T21:42:14.396+0000] {subprocess.py:106} INFO - Try 'streamlit run --help' for help.
[2024-12-19T21:42:14.397+0000] {subprocess.py:106} INFO - 
[2024-12-19T21:42:14.399+0000] {subprocess.py:106} INFO - Error: Invalid value: File does not exist: ./fintech_dashboard.py
[2024-12-19T21:42:14.666+0000] {subprocess.py:110} INFO - Command exited with return code 2
[2024-12-19T21:42:14.688+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-19T21:42:14.715+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fintech_etl_pipeline, task_id=run_dashboard, run_id=manual__2024-12-19T21:39:28.868330+00:00, execution_date=20241219T213928, start_date=20241219T214211, end_date=20241219T214214
[2024-12-19T21:42:14.784+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T21:42:14.785+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 42 for task run_dashboard (Bash command failed. The command returned a non-zero exit code 2.; 389)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-19T21:42:14.843+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-19T21:42:14.872+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-19T21:42:14.874+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
