[2024-12-21T15:18:45.226+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-21T15:18:45.266+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fintech_etl_pipeline.load_to_db manual__2024-12-21T15:18:17.684624+00:00 [queued]>
[2024-12-21T15:18:45.289+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fintech_etl_pipeline.load_to_db manual__2024-12-21T15:18:17.684624+00:00 [queued]>
[2024-12-21T15:18:45.290+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-21T15:18:45.339+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_to_db> on 2024-12-21 15:18:17.684624+00:00
[2024-12-21T15:18:45.349+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=599) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-21T15:18:45.352+0000] {standard_task_runner.py:72} INFO - Started process 608 to run task
[2024-12-21T15:18:45.352+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fintech_etl_pipeline', 'load_to_db', 'manual__2024-12-21T15:18:17.684624+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/fintech_dag.py', '--cfg-path', '/tmp/tmpre7jqmua']
[2024-12-21T15:18:45.357+0000] {standard_task_runner.py:105} INFO - Job 104: Subtask load_to_db
[2024-12-21T15:18:45.435+0000] {task_command.py:467} INFO - Running <TaskInstance: fintech_etl_pipeline.load_to_db manual__2024-12-21T15:18:17.684624+00:00 [running]> on host b2048de23098
[2024-12-21T15:18:45.566+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Zeyad_Habash' AIRFLOW_CTX_DAG_ID='fintech_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-12-21T15:18:17.684624+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-21T15:18:17.684624+00:00'
[2024-12-21T15:18:45.567+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-21T15:18:49.101+0000] {logging_mixin.py:190} INFO - Connected to Database
[2024-12-21T15:18:49.104+0000] {logging_mixin.py:190} INFO - Writing cleaned dataset to database
[2024-12-21T15:18:49.204+0000] {logging_mixin.py:190} INFO - Cleaned Table fintech_data_MET_P1_52_16824 already exists.
[2024-12-21T15:18:49.207+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-21T15:18:49.223+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-21T15:18:49.224+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fintech_etl_pipeline, task_id=load_to_db, run_id=manual__2024-12-21T15:18:17.684624+00:00, execution_date=20241221T151817, start_date=20241221T151845, end_date=20241221T151849
[2024-12-21T15:18:49.300+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-21T15:18:49.331+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-21T15:18:49.334+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
