[2024-12-19T23:14:56.768+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T23:14:56.790+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fintech_etl_pipeline.run_dashboard manual__2024-12-19T23:14:40.082635+00:00 [queued]>
[2024-12-19T23:14:56.799+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fintech_etl_pipeline.run_dashboard manual__2024-12-19T23:14:40.082635+00:00 [queued]>
[2024-12-19T23:14:56.799+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-19T23:14:56.814+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_dashboard> on 2024-12-19 23:14:40.082635+00:00
[2024-12-19T23:14:56.822+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=257) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-19T23:14:56.824+0000] {standard_task_runner.py:72} INFO - Started process 266 to run task
[2024-12-19T23:14:56.824+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fintech_etl_pipeline', 'run_dashboard', 'manual__2024-12-19T23:14:40.082635+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/fintech_dag.py', '--cfg-path', '/tmp/tmp1rremnv2']
[2024-12-19T23:14:56.827+0000] {standard_task_runner.py:105} INFO - Job 82: Subtask run_dashboard
[2024-12-19T23:14:56.881+0000] {task_command.py:467} INFO - Running <TaskInstance: fintech_etl_pipeline.run_dashboard manual__2024-12-19T23:14:40.082635+00:00 [running]> on host b2048de23098
[2024-12-19T23:14:56.976+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Zeyad_Habash' AIRFLOW_CTX_DAG_ID='fintech_etl_pipeline' AIRFLOW_CTX_TASK_ID='run_dashboard' AIRFLOW_CTX_EXECUTION_DATE='2024-12-19T23:14:40.082635+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-19T23:14:40.082635+00:00'
[2024-12-19T23:14:56.977+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T23:14:56.993+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-19T23:14:56.994+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'streamlit run /opt/***/dags/fintech_dashboard.py -- --filename /opt/***/data/fintech_clean.parquet -- --lookup_table_filename /opt/***/data/lookup_table.csv']
[2024-12-19T23:14:57.009+0000] {subprocess.py:99} INFO - Output:
[2024-12-19T23:14:58.496+0000] {subprocess.py:106} INFO - 
[2024-12-19T23:14:58.496+0000] {subprocess.py:106} INFO - Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.
[2024-12-19T23:14:58.497+0000] {subprocess.py:106} INFO - 
[2024-12-19T23:14:58.902+0000] {subprocess.py:106} INFO - 
[2024-12-19T23:14:58.903+0000] {subprocess.py:106} INFO -   You can now view your Streamlit app in your browser.
[2024-12-19T23:14:58.903+0000] {subprocess.py:106} INFO - 
[2024-12-19T23:14:58.904+0000] {subprocess.py:106} INFO -   Local URL: http://localhost:8501
[2024-12-19T23:14:58.904+0000] {subprocess.py:106} INFO -   Network URL: http://172.18.0.6:8501
[2024-12-19T23:14:58.905+0000] {subprocess.py:106} INFO -   External URL: http://154.178.37.101:8501
[2024-12-19T23:14:58.906+0000] {subprocess.py:106} INFO - 
[2024-12-19T23:15:04.643+0000] {subprocess.py:106} INFO - usage: fintech_dashboard.py [-h] --filename FILENAME
[2024-12-19T23:15:04.644+0000] {subprocess.py:106} INFO - fintech_dashboard.py: error: unrecognized arguments: -- --lookup_table_filename /opt/***/data/lookup_table.csv
[2024-12-19T23:16:07.623+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-12-19T23:16:07.625+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-19T23:16:07.627+0000] {process_utils.py:132} INFO - Sending 15 to group 266. PIDs of all processes in the group: [268, 266]
[2024-12-19T23:16:07.627+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 266
[2024-12-19T23:16:07.628+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-19T23:16:07.629+0000] {subprocess.py:117} INFO - Sending SIGTERM signal to process group
[2024-12-19T23:16:07.647+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-12-19T23:16:07.653+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fintech_etl_pipeline, task_id=run_dashboard, run_id=manual__2024-12-19T23:14:40.082635+00:00, execution_date=20241219T231440, start_date=20241219T231456, end_date=20241219T231607
[2024-12-19T23:16:07.673+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T23:16:07.922+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=268, status='terminated', started='23:14:56') (268) terminated with exit code None
[2024-12-19T23:16:07.923+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=266, status='terminated', exitcode=2, started='23:14:55') (266) terminated with exit code 2
